version: 2.1
jobs:
  build-image:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout
  
      - run:
          name: "Docker Login"
          command: |
            echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin 

      - run:
          name: "Docker Build"
          command: |
            docker build -t yashprime07/circlecitest .
      
      - run:
          name: "Docker Push"
          command: |
            docker push yashprime07/circlecitest 


workflows:
  build-image: 
    jobs:
      - build-image