version: 2.1
jobs:
  build-image:
    machine: # executor type
      image: ubuntu-2004:202010-01 

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Docker Login"
          command: |
            echo ${DOCKER_PASSWORD} | docker login  docker login -u ${DOCKER_USER} -password-stdin Yash@1234

      - run:
          name: "Docker Build"
          command: |
            docker build -t yashprime07/circlecitest .


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello