apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy
on:
  workflow_dispatch: {}
jobs:
  deploy:
    environment: "Mu-Nodeapp\t"
    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: Login to AWS
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - uses: cloudbees-io/checkout@v1
        name: Checkout
        with:
          repository: Yashprime1/genzinfra-cloudformation
          ref: master
          token: ${{ vars.GIT_TOKEN }}
      - uses: docker://python:3-alpine3.20
        name: Replace Prod
        shell: sh
        run: |
          jq --arg new_image "yashprime07/circlecitest" '.Stacks[${{ vars.Region }}][${{ vars.StackName }}].Parameters.Image = $new_image' input.json > output.json
      - uses: docker://python:3-alpine3.20
        name: Install Requirements and Deploy
        shell: sh
        run: |
          pip3 install cfstack tabulate
          python3 execute.py 
