apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy Mu-Staging-1
on:
  workflow_dispatch: {}
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
        with:
          repository: Yashprime1/genzinfra-cloudformation
          ref: master
          token: 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
      - name: Install Requirements
        uses: docker://python:3-alpine
        shell: sh
        run: |
          pip3 install cfstack tabulate
          python3 execute.py 
