apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: {}
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout Repo
        with:
          provider: GitHub
          repository: Yashprime1/NodeJsApp
          ref: main
          token: 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
          
      - name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io # or docker.io
          username: ${{ vars.QUICKSTART_DOCKER_USERNAME }}
          password: ${{ secrets.QUICKSTART_DOCKER_PASSWORD }}
      
      - name: Docker build
        uses: linux
        shell: sh
        run: |
          docker build -t yashprime07/circlecitest .
      
      - name: Docker publish
        uses: linux
        shell: sh
        run: |
            docker push yashprime07/circlecitest 
      