apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: {}
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout Repo
        with:
          provider: GitHub
          repository: Yashprime1/NodeJsApp
          ref: main
          token: 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
      - name: build code
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          pwd
          ls
          docker build .