name: Build and Push Docker Image
run-name: ${{ github.ref_name }}-${{ github.run_number }}
on:
  push:
    branches:
      - "*"


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      - name: Docker Build
        run: docker build -t yashprime07/circlecitest:${{ github.ref_name }}-${{ github.run_number }} .

      - name: Docker Push
        run: docker push yashprime07/circlecitest:${{ github.ref_name }}-${{ github.run_number }}

      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
        env:
          OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
          OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
          
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'NodeJS Project'
          release_number: ${{ github.ref_name }}-${{ github.run_number }}
          git_ref: ${{ github.ref }}
          git_commit: ${{ github.event.after || github.event.pull_request.head.sha }}
        env:
          OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
          OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
